---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
canonifyurls: true
indexes:
    category: "categories"
    tag: "tags"
baseurl: "http://radnor.github.io/"
title: "bitbun"
params:
    Description: "A place for me."
    AuthorName: "Kevin Lo"
    GitHubUser: "radnor"
...